# HashR Build Pipeline

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

strategy:
  matrix:
   'Ubuntu Latest':
     image: 'ubuntu-latest'
   'Windows Latest':
     image: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  rid: 'linux-x64'
  projectPath: 'test-web-api'

steps:
    - task: UseDotNet@2
      inputs:
        version: '8.0.x'
        packageType: sdk
        includePreviewVersions: true
    
    - task: DotNetCoreCLI@2
      displayName: "Restore"
      inputs:
        command: 'restore'
        projects: '$(projectPath)/*.csproj'
        restoreArguments: '-r $(rid) /p:Configuration="$(buildConfiguration)"'

    - task: DotNetCoreCLI@2
      displayName: "Build"
      inputs:
        command: 'build'
        projects: '$(projectPath)/*.csproj'
        arguments: '-r $(rid) --self-contained true --configuration "$(buildConfiguration)" --no-restore'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        projects: '$(projectPath)/*.csproj'
        publishWebProjects: false
        arguments: '-r $(rid) --self-contained true --configuration "$(BuildConfiguration)" --no-build --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'test-web-api'